Signals processing
open-telemetry/opentelemetry-java-contrib pull request #1014
Opened 2023-08-23 16:19 UTC by LikeTheSalad

**Description:**

Feature addition - Tools for globally processing signal data items in order to allow for:
- Modification
- Filtering

As part of the [Splunk Android SDK donation](https://github.com/open-telemetry/community/issues/1400), some of the items requested from the community were related to moving generic tools used in the Splunk code over to the java-contrib repo. Some of these tools enabled [filtering spans](https://github.com/open-telemetry/opentelemetry-android/blob/main/instrumentation/src/main/java/io/opentelemetry/android/export/FilteringSpanExporterBuilder.java) based on predefined predicates as well as [adding attributes](https://github.com/open-telemetry/opentelemetry-android/blob/c911c819f2922657eb85a178c90f8d2318f6cadb/instrumentation/src/main/java/io/opentelemetry/android/GlobalAttributesSpanAppender.java#L15) to them.

The proposed tools in this PR aren't exact replicas of the classes used in the Splunk SDK although they aim to enable the same use cases (signal modification and filtering) not only for spans but also for logs and metrics in a quite generic way that should allow for more use cases to be supported, albeit in a less verbose way, but flexible enough to be further extended to add more specific use cases on top, such as "rejectSpansNamed()" and "rejectSpansWithAttributesMatching()" for example, as some of the ones currently available [in here](https://github.com/open-telemetry/opentelemetry-android/blob/main/instrumentation/src/main/java/io/opentelemetry/android/export/FilteringSpanExporterBuilder.java).

There are no defined guidelines on how to accomplish this functionality, so what I'm proposing here is just a way to do so that I consider simple and flexible enough to accommodate different use cases. So I'm open to any alternatives or adjustments that could improve this feature in any way!

**How it works**

There's an [Interceptor](https://github.com/LikeTheSalad/opentelemetry-java-contrib/blob/signals-processing/processors/src/main/java/io/opentelemetry/contrib/interceptor/api/Interceptor.java) interface that can modify or eliminate a signal right before it gets exported. This example shows how to modify and/or filter a span out from exporting:

```java
    InMemorySpanExporter myExporter = InMemorySpanExporter.create();
    ComposableInterceptor interceptor = new ComposableInterceptor();
    Tracer tracer = createTracerWithExporter(new InterceptableSpanExporter(myExporter, interceptor));

    // This interceptor will modify all the spans by adding a new attr.
    interceptor.add(
        spanData -> {
          ModifiableSpanData modified = new ModifiableSpanData(spanData);
          modified.attributes.put("global.attr", "from interceptor");
          return modified;
        });

    // This interceptor will prevent some spans from getting exported:
    interceptor.add(
        spanData -> {
          if (spanData.getName().endsWith("deleted")) {
            return null;
          }
          return spanData;
        });

     // All the spans will go through both interceptors when getting exported
    tracer.spanBuilder("My Span").startSpan()//etc...
```

You can find more examples in the [tests](https://github.com/LikeTheSalad/opentelemetry-java-contrib/tree/signals-processing/processors/src/test/java/io/opentelemetry/contrib/interceptor) added as part of this PR.

**Existing Issue(s):**

**Testing:**

Unit tests

**Documentation:**

**Outstanding items:**

2023-08-23 16:53 UTC, breedx-splk requested changes
Let's use composition here instead. Recommend:

* Remove `Interceptor` interface.
* Rename `Interceptable` to `Interceptor` and make it `final`
* Remove `extends ....` from each of the exporters.
* Add constructor arg and field of type `Interceptor` to each exporter
* Call `interceptor.interceptAll()` in the export method.

2023-08-23 16:53 UTC, breedx-splk commented on .github/component_owners.yml
> +    - ?
You can add me here. I think the literal `?` breaks things.

2023-08-23 16:53 UTC, breedx-splk commented on processors/src/main/java/io/opentelemetry/contrib/interceptor/common/Interceptable.java
> +/** Base class to reuse the code related to intercepting signals. */
I strongly believe that we should not use object inheritance as a mechanism for reusing code.

2023-08-23 16:59 UTC, breedx-splk commented on processors/src/main/java/io/opentelemetry/contrib/interceptor/common/Interceptable.java
> +  private final Set<Interceptor<T>> interceptors = new HashSet<>();
I could think of a few contrived scenarios where order might matter. I'd use a list.

2023-08-24 12:12 UTC, LikeTheSalad commented
> Let's use composition here instead. Recommend:
> 
> Rename Interceptable to MultiInterceptor or something and make it final It might also implement Interceptor<Collection<T>>
> Remove extends .... from each of the exporters.
> Add constructor arg and field of type MultiInterceptor (or the interface) to each exporter
> Call interceptor.interceptAll() in the export method.

Sounds good, I've applied the changes you mentioned with some small diffs, for the multi interceptor name I went with "ComposableInterceptor" and for the exporters' constructor arg for an interceptor I went with the interface `Interceptor` instead of any implementation to allow users to use any kind of implementation they'd like. Also, the `interceptAll` method was made a default Interceptor method since it seems appropriate as a reusable functionality regardless of the implementation.

2023-08-24 13:54 UTC, mateuszrzeszutek commented on processors/src/main/java/io/opentelemetry/contrib/interceptor/api/Interceptor.java
> +  T intercept(T item);
```suggestion
  @Nullable
  T intercept(T item);
```

2023-08-24 13:54 UTC, mateuszrzeszutek commented on processors/src/main/java/io/opentelemetry/contrib/interceptor/common/ComposableInterceptor.java
> +  private final List<Interceptor<T>> interceptors = new ArrayList<>();
Typically, when using the `BatchSpanProcessor` sending the telemetry data happens on a separate thread; consider using `CopyOnWriteArrayList` instead
```suggestion
  private final List<Interceptor<T>> interceptors = new CopyOnWriteArrayList<>();
```

2023-08-24 13:54 UTC, mateuszrzeszutek commented on processors/src/main/java/io/opentelemetry/contrib/interceptor/common/ComposableInterceptor.java
> +    }
Assuming `interceptors` is an instance of `CopyOnWriteArrayList`:
```suggestion
    interceptors.addIfAbsent(interceptor);
```

2023-08-24 13:54 UTC, mateuszrzeszutek commented on processors/src/main/java/io/opentelemetry/contrib/interceptor/InterceptableLogRecordExporter.java
> +public class InterceptableLogRecordExporter implements LogRecordExporter {
Nit: all of these exporters can be `final`
```suggestion
public final class InterceptableLogRecordExporter implements LogRecordExporter {
```

2023-08-24 13:54 UTC, mateuszrzeszutek commented on processors/src/test/java/io/opentelemetry/contrib/interceptor/InterceptableLogRecordExporterTest.java
> +  public void setUp() {
Nit: JUnit 5 tests & lifecycle methods can be package-private
```suggestion
  void setUp() {
```

2023-08-25 08:22 UTC, LikeTheSalad commented
Thanks @mateuszrzeszutek ! I've applied your suggestions.

2023-08-25 12:33 UTC, mateuszrzeszutek approved these changes
👍

2023-09-05 20:23 UTC, trask commented
@breedx-splk could you give this another look? thx

2023-09-07 21:46 UTC, breedx-splk approved these changes

2023-09-07 22:56 UTC, merged