Move to io.opentelemetry.semconv:opentelemetry-semconv
open-telemetry/opentelemetry-java-contrib pull request #1055
Opened 2023-09-27 07:10 UTC by deki

**Description:**

[io.opentelemetry:opentelemetry-semconv](https://search.maven.org/artifact/io.opentelemetry/opentelemetry-semconv) was moved to [io.opentelemetry.semconv:opentelemetry-semconv](https://search.maven.org/artifact/io.opentelemetry.semconv/opentelemetry-semconv) and the former is now deprecated as per https://github.com/open-telemetry/opentelemetry-java/pull/5786.

**Existing Issue(s):**

#1044 

**Testing:**

Unittest execution

**Documentation:**

**Outstanding items:**

2023-09-27 12:05 UTC, kenfinnigan approved these changes
Thanks @deki

2023-09-29 09:58 UTC, cyrille-leclerc requested changes
Thank you very much for your contribution.
I'm sorry but I propose a slightly different path forward:

I propose to decouple and solve later the question of adopting the new convention and to implement it aligning with the OTel Java Auto Instr that added a config flag `OTEL_SEMCONV_STABILITY_OPT_IN` / `otel.semconv-stability.opt-in`.
I created a PR narrowed down to the change of lib:
* https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1059

2023-09-29 09:58 UTC, cyrille-leclerc commented on maven-extension/src/main/java/io/opentelemetry/maven/handler/GoogleJibBuildHandler.java
> +    spanBuilder.setAttribute(SemanticAttributes.URL_FULL, "https://" + registryHostname);
I propose to decouple and solve later the question of adopting the new convention and to implement it aligning with the OTel Java Auto Instr that added a config flag `OTEL_SEMCONV_STABILITY_OPT_IN` / `otel.semconv-stability.opt-in`.
I created a PR narrowed down to the change of lib:
* https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1059

2023-09-29 11:28 UTC, cyrille-leclerc commented
FYI https://github.com/cyrille-leclerc/opentelemetry-java-contrib/tree/support-stable-http-semconv

2024-05-08 10:41 UTC, laurit commented
Closing in favor of https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1299

2024-05-08 10:41 UTC, closed without merging