Update handlers in jfr-streaming to match spec
open-telemetry/opentelemetry-java-contrib pull request #616
Opened 2022-11-21 18:51 UTC by roberttoyonaga

**Description:**
These changes try to update the existing JFR streaming handlers to match the [specification here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics).  I think this is needed because it seems as though the handler implementations and the spec have fallen a bit out of sync. 

**Testing:**

Tests were adjusted accordingly to match the updated handler implementations.

**Outstanding items and questions:**

Tests for specific GC implementations (G1, parallel) have been omitted. I am not sure of a good way to guarantee a specific implementation is used for specific tests. 

None of the metrics `process.runtime.jvm.memory.*` will include the`Attribute` pair  (`type`,`"nonheap"`).  Question: Doesn't non-heap memory fall under the `process.runtime.jvm.buffer.*` metrics? 

Not all of the pool names of the metrics `process.runtime.jvm.memory.*` are covered yet. This is in part because we require JDK JFR support to actually emit data for missing pools in JFR events, and partly because more handlers for other GC implementations need to be written in the future.

2022-11-28 23:05 UTC, breedx-splk requested changes
Thanks for getting these updates in place, much appreciated! Just had a few ideas but looks good overall.

2022-11-29 15:47 UTC, roberttoyonaga commented on jfr-streaming/src/main/java/io/opentelemetry/contrib/jfr/metrics/internal/memory/ParallelHeapSummaryHandler.java
> +          committedYoung = youngSpace.getLong(COMMITTED_SIZE);
That's a good idea! I implemented your suggestion

2022-11-29 23:37 UTC, trask commented
thx!

2022-11-29 23:38 UTC, trask approved these changes

2022-11-29 23:38 UTC, merged